version: '3.1'
services:
  db:
    image: mongo:3.4.23-xenial
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: always
  api:
    build: .
    ports:
      - 8080:80
    environment:
      PORT: 80
      DB_URL: localhost:27017
      DB_NAME: users
      DB_USERNAME: root
      DB_PASSWORD: example
    restart: always
