version: '3.1'
services:
  db:
    image: mongo:3.4.23-xenial
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  api:
    build: .
    restart: always
    ports:
      - 8081:80
    environment:
      PORT: 80
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example